include ../../../setup.mk

all: $(wavfiles)

2601a.wav: eightpoint.con
2602.wav: eightpoint.con

2603a.wav: fox.con hello.con
2603b.wav: fox.con hello.con
2603c.wav: fox.con hello.con
2603.wav: fox.con hello.con
2604.wav: gaussreverb.con
2605a.wav: bassdrum.con lowpass1khz.con
2605a.wav: lowpass300hz.con lowpass3khz.con rimshot.con
2605b.wav: bassdrum.con lowpass1khz.con lowpass300hz.con lowpass3khz.con rimshot.con
2605c.wav: bassdrum.con lowpass1khz.con lowpass300hz.con lowpass3khz.con rimshot.con
2606a.wav: cymbal.con hello.con highpass1khz.con highpass300hz.con highpass3khz.con
2606b.wav: cymbal.con hello.con highpass1khz.con highpass300hz.con highpass3khz.con
2606c.wav: cymbal.con hello.con highpass1khz.con highpass300hz.con highpass3khz.con

eightpoint.con: eightpoint.aif
gaussreverb.con: gaussreverb.aif
bassdrum.con: bassdrum.aif
cymbal.con: cymbal.aif
fox.con: fox.aif
hello.con: hello.aif
highpass1khz.con: highpass1khz.aif
highpass300hz.con: highpass300hz.aif
highpass3khz.con: highpass3khz.aif
lowpass1khz.con: lowpass1khz.aif
lowpass300hz.con: lowpass300hz.aif
lowpass3khz.con: lowpass3khz.aif
rimshot.con: rimshot.aif

include ../../../rules.mk
