include ../../setup.mk

all: 

#303emu.wav

ok:
	cdelay.wav
	drumkit1.orc
	enhance.orc

#guitar2.wav: guitar2.orc ??

# guitar.orc
# lpf18.orc
# megadist.orc
# seq303.orc
# stringphaser.orc
# sync.orc


include ../../rules.mk
